export const STOP_WORDS = new Set([
  'a', 'about', 'above', 'after', 'again', 'against', 'all', 'also', 'am',
  'an', 'and', 'another', 'any', 'are', 'arent', 'around', 'as', 'at',
  'back', 'be', 'because', 'been', 'before', 'being', 'below', 'between',
  'both', 'but', 'by', 'came', 'can', 'cant', 'cannot', 'come', 'could',
  'couldnt', 'day', 'did', 'didnt', 'do', 'does', 'doesnt', 'doing', 'done',
  'dont', 'down', 'during', 'each', 'even', 'every', 'few', 'for', 'from',
  'further', 'get', 'give', 'go', 'goes', 'going', 'got', 'had', 'hadnt',
  'has', 'hasnt', 'have', 'havent', 'having', 'he', 'hed', 'hell', 'hes',
  'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'hows',
  'i', 'id', 'if', 'ill', 'im', 'in', 'into', 'is', 'isnt', 'it', 'its',
  'ive', 'itself', 'just', 'know', 'last', 'left', 'let', 'lets', 'like',
  'look', 'made', 'make', 'may', 'me', 'might', 'more', 'most', 'much',
  'mustnt', 'my', 'myself', 'need', 'never', 'no', 'nor', 'not', 'now',
  'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought', 'our', 'ours',
  'ourselves', 'out', 'over', 'own', 'part', 'place', 'put', 'right',
  'same', 'say', 'see', 'set', 'shant', 'she', 'shed', 'shell', 'shes',
  'should', 'shouldnt', 'since', 'so', 'some', 'such', 'take', 'than',
  'that', 'thats', 'the', 'their', 'theirs', 'them', 'themselves', 'then',
  'there', 'theres', 'these', 'they', 'theyd', 'theyll', 'theyre', 'theyve',
  'think', 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up',
  'us', 'very', 'want', 'was', 'wasnt', 'way', 'we', 'wed', 'well', 'went',
  'were', 'werent', 'weve', 'what', 'whats', 'when', 'whens', 'where',
  'wheres', 'which', 'while', 'who', 'whos', 'whom', 'why', 'whys', 'will',
  'with', 'wont', 'would', 'wouldnt', 'year', 'you', 'youd', 'youll',
  'your', 'youre', 'yours', 'yourself', 'yourselves', 'youve',
]);
